version: '3.8'
services:
  pokepro-db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokepro_development
    volumes:
      - ./db_dump.tar:/db_dump.tar
      - ./restore.sh:/docker-entrypoint-initdb.d/restore.sh
      - db_data:/var/lib/postgresql/data
  pokepro-app:
    build: .
    ports:
      - '3001:3001'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokepro_development
      POSTGRES_HOST: pokepro-db
    depends_on:
      - pokepro-db

volumes:
  db_data:
