version: '3.8'

services:
  app:
    build: .
    environment:
      - PORT=3001
      - POSTGRES_HOST=db
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pokepro_development
    ports:
      - '3001:3001'
    depends_on:
      - db

  db:
    image: 'postgres:13'
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pokepro_development
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
